### ISSUE TITLE
Crash when set app in background

### ISSUE THREAD

**Issue by MSL-BIT** [RafaelBarbosatec/qr_code_dart_scan#28]
Hi,

I installed the example app on my Android device. When I put the app in background during the camera is running I got the following exception:

flutter: CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)

How can we avoid this?

**Comment by RafaelBarbosatec** [comment]
Hi @MSL-BIT !
Thanks for testing. I'll take a look at it.

**Comment by RafaelBarbosatec** [comment]
Please try use the version 0.9.1

**Comment by shuwenli-tomo** [comment]
HI,

I am using Version 0.9.8, still have this issue, the log is as below. Should be the same issue as above.

E/flutter (26676): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)
E/flutter (26676): #0      CameraController._throwIfNotInitialized (package:camera/src/camera_controller.dart:897:7)
E/flutter (26676): #1      CameraController.buildPreview (package:camera/src/camera_controller.dart:650:5)
E/flutter (26676): #2      CameraPreview.build.<anonymous closure> (package:camera/src/camera_preview.dart:35:57)
E/flutter (26676): #3      _ValueListenableBuilderState.build (package:flutter/src/widgets/value_listenable_builder.dart:141:26)

**Comment by RafaelBarbosatec** [comment]
Try update the package to the latest version pls.

**Comment by shuwenli-tomo** [comment]
Upgrade to version 0.10.0, the issue still exists.

Reproduce: 
1. open the scan view
2. allow camera access
3. put app to background

Error:
The following CameraException was thrown:
CameraException(Disposed CameraController, buildPreview() was called on a disposed CameraController.)

**Comment by phamdat080598** [comment]
I got the same issue in qr_code_dart_scan: 0.9.4.

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: CameraException(Disposed CameraController, startImageStream() was called on a disposed CameraController.)
       at CameraController._throwIfNotInitialized(camera_controller.dart:897)
       at CameraController.startImageStream(camera_controller.dart:490)
       at QRCodeDartScanController.startScan(qr_code_dart_scan_controller.dart:203)
       at QRCodeDartScanController._initController(qr_code_dart_scan_controller.dart:127)
       at QRCodeDartScanController.config(qr_code_dart_scan_controller.dart:105)
       at QRCodeDartScanViewState._initController(qr_code_dart_scan_view.dart:139)

Does anyone know how to solve this problem?
