### ISSUE TITLE
App Crash when go back to home screen

### ISSUE THREAD

**Issue by fondoger** [RafaelBarbosatec/qr_code_dart_scan#29]
```log
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Valid value range is empty: 1
#0      List.[] (dart:core-patch/growable_array.dart)
#1      IsolatePool.runTask (package:qr_code_dart_scan/src/util/isolate_pool.dart:52:32)
isolate_pool.dart:52
#2      IsolateDecoder.decodeCameraImage (package:qr_code_dart_scan/src/decoder/isolate_decoder.dart:66:34)
isolate_decoder.dart:66
#3      QRCodeDartScanDecoder.decodeCameraImage (package:qr_code_dart_scan/src/decoder/qr_code_dart_scan_decoder.dart:59:45)
qr_code_dart_scan_decoder.dart:59
#4      QRCodeDartScanController._processImage (package:qr_code_dart_scan/src/qr_code_dart_scan_controller.dart:162:49)
qr_code_dart_scan_controller.dart:162
#5      QRCodeDartScanController._imageStream (package:qr_code_dart_scan/src/qr_code_dart_scan_controller.dart:158:5)
qr_code_dart_scan_controller.dart:158
#6      CameraController.startImageStream.<anonymous closure> (package:camera/src/camera_controller.dart:508:20)
camera_controller.dart:508
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
zone.dart:1594
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
stream_impl.dart:365
#9      _DelayedData.perform (dart:async/stream_impl.dart:541:14)
stream_impl.dart:541
#10     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
stream_impl.dart:646
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
stream_impl.dart:617
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
schedule_microtask.dart:40
```

**Comment by RafaelBarbosatec** [comment]
Please try use the version 0.9.1
